<img style="float: left;;" src='Figures/alinco.png' height="100"/></a>

# <center> <font color= #000047>  Librería NumPy</font> </center>




NumPy es una poderosa librería de álgebra lineal para Python. Lo que lo hace tan importante es que casi todas las librerías en el ecosistema de <a href='https://pydata.org/'>PyData</a> (pandas, scipy, scikit-learn, etc.) utilizan NumPy como uno de sus principales componentes básicos. 

NumPy también es increíblemente rápido, ya que tiene enlaces a bibliotecas C.

Aquí repasaremos los conceptos básicos de NumPy.

## Usando NumPy


In [1]:
import numpy as np


NumPy tiene muchas funciones y capacidades integradas. No veremos todos, nos centraremos en algunos de los aspectos más importantes de NumPy qué nos serán de utilidad en el curso como son: vectores, arreglos, matrices y generación de números aleatorios. 

# Arreglos en NumPy 

Los arreglos de NumPy son la principal forma en que utilizaremos esta librería a lo largo del curso. Los arreglos en NumPy se construyen de dos formas: vectores y matrices. Los vectores son matrices estrictamente unidimensionales (1D) y las matrices son elementos en 2D (pero se debe tener en cuenta que una matriz puede tener solo una fila o una columna) no son estrictamente cuadradas.

## Creando Arreglos en NumPy

### De una Lista de Python 

Podemos crear un arreglo directamente de una lista o listas de listas:



In [4]:
l1 = [1,2,3,4]
l1

[1, 2, 3, 4]

In [6]:
a = np.array(l1)
a

array([1, 2, 3, 4])

In [7]:
type(a)

numpy.ndarray

In [8]:
a.shape

(4,)

In [9]:
m1 = np.array([[1,2,3],[2,3,4],[5,6,7]])

In [10]:
m1.shape

(3, 3)

## Métodos incorporados en NumPy

Hay muchas formas de como generar arreglos usando métodos incorporados.

### arange

Devuelve valores espaciados uniformemente dentro de un intervalo dado. [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.arange.html)]

In [12]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### Creando arreglos de Ceros (zeros) y Unos (ones)

Podemos generar matrices de ceros ó unos. [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.zeros.html)]

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### linspace 
Este método devuelve números espaciados uniformemente durante un intervalo especificado.[[referencia](https://www.numpy.org/devdocs/reference/generated/numpy.linspace.html)]

In [22]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [23]:
x = np.linspace(0,100)
def f(x):
    return x**2 + 3*x

f(x)

array([0.00000000e+00, 1.02873803e+01, 2.89046231e+01, 5.58517284e+01,
       9.11286964e+01, 1.34735527e+02, 1.86672220e+02, 2.46938776e+02,
       3.15535194e+02, 3.92461474e+02, 4.77717618e+02, 5.71303623e+02,
       6.73219492e+02, 7.83465223e+02, 9.02040816e+02, 1.02894627e+03,
       1.16418159e+03, 1.30774677e+03, 1.45964182e+03, 1.61986672e+03,
       1.78842149e+03, 1.96530612e+03, 2.15052062e+03, 2.34406497e+03,
       2.54593919e+03, 2.75614327e+03, 2.97467722e+03, 3.20154102e+03,
       3.43673469e+03, 3.68025823e+03, 3.93211162e+03, 4.19229488e+03,
       4.46080800e+03, 4.73765098e+03, 5.02282382e+03, 5.31632653e+03,
       5.61815910e+03, 5.92832153e+03, 6.24681383e+03, 6.57363599e+03,
       6.90878800e+03, 7.25226989e+03, 7.60408163e+03, 7.96422324e+03,
       8.33269471e+03, 8.70949604e+03, 9.09462724e+03, 9.48808830e+03,
       9.88987922e+03, 1.03000000e+04])

In [ ]:
#...plot(x,f(x))

<font color=green>Note que `.linspace()` *incluye* el valor de paro. Para obtener un arreglo con fracciones comunes, hay que aumentar el numero de elementos:</font>

### eye

Mediante este método podemos crear la matriz identidad.[[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.eye.html)]

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random 
Numpy también tiene muchas formas de crear arreglos de números aleatorios:

### rand

Mediante este método podemos crear un arreglo de un tamaño dado con muestras aleatorias de una distribución uniforme en el intervalo ``[0, 1)``.[[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.rand.html)]

In [27]:
np.random.rand(50)

array([0.81858501, 0.54620695, 0.78957953, 0.65570495, 0.2100084 ,
       0.48948306, 0.15730566, 0.20165415, 0.63154298, 0.1127942 ,
       0.68109759, 0.97598039, 0.88568188, 0.12844572, 0.80191367,
       0.22863662, 0.91742032, 0.88594259, 0.59303956, 0.32578327,
       0.81094986, 0.2745914 , 0.6769384 , 0.88756026, 0.79949895,
       0.66052251, 0.80053711, 0.9458561 , 0.29243313, 0.65961761,
       0.19882067, 0.28604316, 0.92830288, 0.38862047, 0.93445909,
       0.11609276, 0.24750198, 0.81412706, 0.86840798, 0.21226202,
       0.28179043, 0.50735947, 0.10408487, 0.55290061, 0.95670335,
       0.08678596, 0.30737741, 0.66745198, 0.71591288, 0.59632708])

### randn

Este método devuelve una muestra (o muestras) de la distribución "normal estándar" [σ = 1] A diferencia de **rand**, que es uniforme, es más probable que aparezcan valores más cercanos a cero. [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randn.html)]


In [28]:
#Utilizado para desviacion estandar como la campana de gauss
np.random.randn(10)

array([-0.66856916,  0.21805928, -0.17849867, -0.41188929, -0.05710575,
       -0.9575105 , -1.00501009,  1.27418663, -1.37423076, -0.33121417])

### randint
Devuelve números enteros aleatorios de un intervalo `mínimo` (inclusive) a `máximo` (exclusivo).  [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randint.html)]

In [29]:
np.random.randint(1,100,10)

array([90, 33, 43, 16, 12, 68, 72, 37, 53, 50])

### seed
Se puede utilizar para establecer el estado aleatorio, de modo que se puedan reproducir los mismos resultados "aleatorios". [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.seed.html)]

In [35]:
np.random.seed(5)

In [36]:
np.random.seed()

## Atributos y métodos de un Arreglo

Analicemos algunos atributos y métodos útiles para un arreglo:

In [37]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

## Reshape
Devuelve una matriz que contiene los mismos datos con una nueva forma. [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.reshape.html)]

In [38]:
arr.shape

(25,)

In [39]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [40]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [41]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

### max, min, argmax, argmin

Estos son métodos útiles para encontrar valores máximos o mínimos. O para encontrar el índice donde tenemos valores máximos o mínimos:

In [42]:
arr.max(), arr.min()

(24, 0)

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [44]:
arr.argmax()

24

In [45]:
arr.argmin()

0

## Shape

Shape es un atributo que tienen los arreglos (no un método): [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.shape.html)]

In [46]:
arr.shape

(25,)

### dtype

Podemos también obtener el tipo de datos del objeto en el arreglo. [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.dtype.html)]

In [49]:
arr.dtype

dtype('int32')

In [51]:
type(arr)

numpy.ndarray

In [ ]:
# En los arreglos los datos deben ser del mismo tipo.  A diferencia de una lista